name: tests

on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            - name: update npm
              run: npm i -g npm@latest
            - name: Install Node Modules
              run: npm ci
            - name: Install Playwright
              run: npx playwright install --with-deps
            - name: Compile element-vir
              run: npm run compile
            - name: Run All Tests
              run: npm run test:all
